### ISSUE TITLE
Conditions not saving the value field

### ISSUE THREAD

**Issue by gusdgg** [rainlab/notify-plugin#15]
The ConditionBuilder formwidget changes the $_POST superglobal in [L351](https://github.com/rainlab/notify-plugin/blob/master/formwidgets/ConditionBuilder.php#L351)  and [L356](https://github.com/rainlab/notify-plugin/blob/master/formwidgets/ConditionBuilder.php#L356) but due to [this](https://github.com/octobercms/library/commit/fd839047c2d7757f225a8ed60673ca8a20fe7df4) change in https://github.com/octobercms/library, the $_POST superglobal can't be changed directly anymore. So, the value field is not saved.  [This](https://github.com/rainlab/translate-plugin/pull/463) could be changed here too in order to fix it:

Insted of:

`$_POST['condition_data'] = $cache;`

Now should be:

```
$requestData = Request::all();
array_set($requestData, 'condition_data' , $cache);
Request::merge($requestData);        
```

**Comment by LukeTowers** [comment]
@gusdgg could you submit a PR to fix this?

**Comment by gusdgg** [comment]
Sure, I will fix the ActionBuilder formwidget too.

**Comment by w20k** [comment]
@LukeTowers will take it ;)
