### ISSUE TITLE
I cannot save notification, i get "The mail template field is required"

### ISSUE THREAD

**Issue by azahraoui** [rainlab/notify-plugin#19]
Hello,

When i try to save notification rule from 'User' -> 'Is activated' -> Compose a mail message, i choose to send notification to all administrators, i save the rule, and when i save the notification, i get error "The mail template field is required",

When i return to the "Compose a mail message" form, i don't find the data stored.

Hello.

**Comment by arustler** [comment]
I can confirm this bug.. Same here

On Registered -> Compose Mail

Choosing mail template does not get saved

**Comment by tystuyfzand** [comment]
I can confirm this, along with not being able to save any other options on this, though it does appear to be resolved with 75d7123c35a2379215a3196fb511cf5771f9e405.

Perhaps we just need a new version pushed to the OctoberCMS plugin page?

**Comment by w20k** [comment]
You could try out with edge updates enabled.

**Comment by LukeTowers** [comment]
@w20k can you push out a new version with the update notes and a tag? (and tag the other two versions while you're at it?) When you're done that ping me and I'll update it on the marketplace.

**Comment by azahraoui** [comment]
Hello, it is not resolved yet! any update ?

**Comment by azahraoui** [comment]
I have applied this commit and it work perfectly: https://github.com/webmaxx/oc-notify-plugin/commit/dec96f339838b801cdc6138251d4fc7f7b2d8d9f

Thanks to webmaxx

**Comment by w20k** [comment]
@megalogi didn't have time to push a new version, will try to manage it. In a day or two, hopefully. 
That's @LukeTowers bug fixes commit https://github.com/rainlab/notify-plugin/commit/75d7123c35a2379215a3196fb511cf5771f9e405

**Comment by sagjatome** [comment]
Have the same troubles

**Comment by kgosikekana** [comment]
I am also experiencing this issue. Any update on it?

**Comment by sagjatome** [comment]
I am also experiencing this issue. Any update on it?
I think they have no more interest on this plugin

**Comment by mennax** [comment]
@sagjatome @kgosikekana 
I confirm, Updated version here on GitHub fix this issue.

**Comment by LukeTowers** [comment]
Marketplace has been updated.

**Comment by sagjatome** [comment]
I get the Problem again, why?
I have the latest Version.

**Comment by genchev** [comment]
Latest version and same problem

**Comment by daftspunk** [comment]
[Send us an email](https://octobercms.com/contact) for support with this. Thanks!

**Comment by daftspunk** [comment]
This should be fixed in v1.1.2, please update and try again.

**Comment by genchev** [comment]
Still the same problem with v1.1.2.
it seems that after the "Compose a mail message" setting are made, they are
not saved. If I open the settings again after closing the box, they are all
empty.

**Comment by daftspunk** [comment]
@genchev Can you confirm what version of October CMS you are running?

**Comment by genchev** [comment]
1.0.473

**Comment by sagjatome** [comment]
The latest version of October 2.1.22 and Notify 1.1.2  - it works.
