### ISSUE TITLE
Undefined class constant 'CATEGORY_NOTIFICATIONS'

### ISSUE THREAD

**Issue by qroft** [rainlab/notify-plugin#2]
I just saw this plugin in my backend as "recommendation" so i clicked on it and voila: my backend does not work anymore and throws this error:
Undefined class constant 'CATEGORY_NOTIFICATIONS'

```
public function registerSettings()
{
    return [
        'notifications' => [
            'label'       => 'rainlab.notify::lang.notifications.menu_label',
            'description' => 'rainlab.notify::lang.notifications.menu_description',
            'category'    => SettingsManager::CATEGORY_NOTIFICATIONS,
            'icon'        => 'icon-bullhorn',
            'url'         => Backend::url('rainlab/notify/notifications'),
            'permissions' => ['rainlab.notify.manage_notifications'],
            'order'       => 600
        ],
    ];
```

**Comment by daftspunk** [comment]
This plugin is only compatible with Build 420+

**Comment by stelgenhof** [comment]
I experienced exactly the same. Understand that it is only compatible with Build 420+ but how do I recover from this? Don't want to reinstall OctoberCMS again preferably.

**Comment by LukeTowers** [comment]
@stelgenhof do you mean make your October instance work again without this plugin or do you mean make it work with this plugin?

**Comment by stelgenhof** [comment]
@LukeTowers Well, this error appears all the time in the backend so the backend is unusable. In the end I removed the notify plugin files from the plugin folder. That way the backend worked again.

It may be better if plugins that are in beta or for a specific build be marked as such in the UI for example. Just to avoid people experiencing similar issues in the future :)

**Comment by Adrion** [comment]
Same here with Build 431... 
I tried to manually replace the Constant by a string but then I have a creation error : `Call to a member function setCustomData() on null` at `$this->getConditionObject()->setCustomData($this);`

**Comment by LukeTowers** [comment]
To be fair it says it clearly at the [top of the readme](https://github.com/rainlab/notify-plugin#notification-engine) and on [the marketplace](http://octobercms.com/plugin/rainlab-notify). If you have an idea for a specific UI enhancement I'd be welcome to hearing it, but typically we're unwilling to support users of plugins that are unwilling to upgrade to the latest version of October, especially given the amount of work we put in to make sure October base upgrades are as hassle-free as possible for the user. 

Granted 420 is a special case with the switch the Laravel 5.5 and PHP 7, but there aren't really very many good reasons for still using a version of PHP < 7.

**Comment by stelgenhof** [comment]
@LukeTowers Thanks for the update! Next time I will indeed checkout the documentation of plugins :)

In this case, the plugin was causing much harm in the sense that October didn't work anymore. Many users might not immediately checkout the marketplace documentation, so a warning of some sorts in the UI could help users understand about the risk of installing plugins.

Just a nice to have; understand if it's not a priority at the moment.

Cheers! Sacha
