### ISSUE TITLE
Plugin interface not showing up in the settings area

### ISSUE THREAD

**Issue by Nvironmental** [rainlab/notify-plugin#20]
Hi Guys, 

I recently installed the Notify Plugin and it says that the plugin will be located in Settings > Notifications. However, I do not see any menu item related to notify in my settings panel (neither on the top bar). I checked my the folder structure, and the notify plugin does exist within the Plugins > RainLab > Notify but I cannot locate in my setting panel.  

Am I missing something ?  Please Help

**Comment by LukeTowers** [comment]
@Nvironmental you should be able to find it at /backend/rainlab/notify/notifications.

Check your plugin settings to make sure it hasn't been disabled and try running `php artisan october:up` to make sure that its migrations have been run.

**Comment by Nvironmental** [comment]
Hi @LukeTowers by accessing /backend/rainlab/notify/notifications it worked and now it shows properly in the setting panels thank you. 

Still unsure as to why it wasn't showing before. 
It wasn't disabled in setting and since it worked just by accessing the above url, I didn't run ```php artisan october:up``` command

**Comment by bennothommo** [comment]
@Nvironmental It perhaps could've been a caching issue, either browser-side or server-side.
