### ISSUE TITLE
Action class with repeater type field

### ISSUE THREAD

**Issue by webmaxx** [rainlab/notify-plugin#26]
Hello,
How can make an action class with a repeater type field?

_"Unexpected type of array when attempting to save attribute "repeater_field", try adding it to the $jsonable property." on line 751 of /site/vendor/october/rain/src/Database/Model.php_

**Comment by daftspunk** [comment]
Repeater fields are not supported at the moment. We have added this to our internal list of improvements. Thanks!

**Comment by prhost** [comment]
Resurrecting this issue, from what I understand, what prevents the saving of RuleAction is related to `repeater` in this section of `ocrober/rain/src/Database/Model.php`:

![Screenshot 2024-01-25 at 17 30 05](https://github.com/rainlab/notify-plugin/assets/3984760/9632411a-36ad-41da-91d9-db5c1191152d)

I commented out the Exception line, and it saved successfully. After that, the `beforeSave` of the RuleAction model is executed, transferring the data to `config_data` and clearing the previously filled attributes.

Is there a way to bypass this somehow? Perhaps by executing `beforeSave` earlier or by using an attribute in the model to disable this jsonable validation?

**Comment by daftspunk** [comment]
@prhost This line has been removed in OCMS v3.6 for other reasons. It should be fixed when this version is released.
