### ISSUE TITLE
Creates duplicates every time you view settings

### ISSUE THREAD

**Issue by ndcisiv** [rainlab/notify-plugin#3]
Every time I click on Notification Rules in backend Settings, it creates another record for "Send welcome email to user".  Even clicking on one of the rules and deleting it doesn't help because the moment the screen goes back to the list another record is generated.

**Comment by daftspunk** [comment]
I can't seem to replicate this one... hmm.

**Comment by ndcisiv** [comment]
Seems to have fixed itself after [https://github.com/rainlab/notify-plugin/commit/4d423b7a46ff8e532eea4bada8a0a401c8ea1328](https://github.com/rainlab/notify-plugin/commit/4d423b7a46ff8e532eea4bada8a0a401c8ea1328)
