### ISSUE TITLE
[Feature Request] October Backend channel

### ISSUE THREAD

**Issue by mohsin** [rainlab/notify-plugin#30]
I see that the goal of this plugin is to streamline the way notifications are delivered which is great. In addition to doing that, I think there would be a benefit to adding a Backend channel out of the box when this plugin is installed. Basically a way by which a user can set up a way by which notifications are delivered to other backend users based on events occurring and this can show up in the top right as a bell icon with numbered badges showing the number of notifications.

**Comment by daftspunk** [comment]
Thank you for your feedback! We have added this insight to our internal tracker
