### ISSUE TITLE
Can't "Compose an email message" when "A user is registered"

### ISSUE THREAD

**Issue by Zmove** [rainlab/notify-plugin#31]
Hello,

I wanted to use notify to compose an email message when a user is registered. when when I choose the "compose an email message action" I get an error : 

`"htmlspecialchars() expects parameter 1 to be string, array given" on line 580 of /vendor/laravel/framework/src/Illuminate/Support/helpers.php`

With october 471 with all modules up to dates.

Regards,

Alex

**Comment by LukeTowers** [comment]
@Zmove use composer and update to October v1.1

**Comment by daftspunk** [comment]
Tested fine in v2.1.5
