### ISSUE TITLE
Error on create notification condition

### ISSUE THREAD

**Issue by LeoMachado94** [rainlab/notify-plugin#33]
![image](https://user-images.githubusercontent.com/11590935/133173277-c6503125-54a2-40a7-9bd1-6e041719d65d.png)

**Comment by daftspunk** [comment]
Hi @LeoMachado94 

Unfortunately, we could not reproduce this error using v2.1.8 of October CMS and v1.1.0 of this plugin.

Please provide clear step-by-step instructions on how you arrive at this error. Also, make sure you are using the latest versions.

Thanks

**Comment by LeoMachado94** [comment]
Hi, this is versions of packages in project. In the future we plan to update, but now we can't.
"php": "^7.3",
        "october/rain": "1.1.7",
        "october/system": "1.1.6",
        "october/backend": "1.1.6",
        "october/cms": "1.1.6",
        "laravel/framework": "6.20.29",
[...]

**Comment by LeoMachado94** [comment]
When entering through the panel and trying to create a new condition, this error happens, this with classes from the plugin itself, they weren't condition classes created by us.

In backend, click in Notification Rules > + New Notification Rule > User > Registered > Tab Conditions > Add Condition.

![image](https://user-images.githubusercontent.com/11590935/133906605-2da6435c-14b7-49c1-8437-9bbe36a75eda.png)
![image](https://user-images.githubusercontent.com/11590935/133906615-1a84dba0-7a4b-47eb-9860-8ef85a61080f.png)
![image](https://user-images.githubusercontent.com/11590935/133906620-d277be73-4bcc-4a63-a4f9-4a30a53f4c1a.png)
![image](https://user-images.githubusercontent.com/11590935/133906643-29dc9a07-366f-44c7-850b-800b2bd4f5ad.png)
![image](https://user-images.githubusercontent.com/11590935/133906694-186cf4fa-1715-42c4-81f1-ecc78a79f9b4.png)
![image](https://user-images.githubusercontent.com/11590935/133906676-5464b32d-4820-4ba7-aec2-db2623a29ca0.png)

**Comment by daftspunk** [comment]
This should work without errors. Are you using v1.1.0 of this plugin?
