### ISSUE TITLE
Can't create new notification, "Add Notification Rule" form is empty

### ISSUE THREAD

**Issue by kelly001** [rainlab/notify-plugin#37]
Hello!

I installed plugin, but "Add Notification Rule" form at the backend area is not working. After clicking btn "New Notification Rule" from shows, but it is empty and I can not do anything with it but close.

Current October build is 2.2.34
Plugin version is 1.2.1

![Notification Rules  October CMS - Google Chrome](https://user-images.githubusercontent.com/3434414/188720073-e63be00a-51cc-408f-a1fc-563d6da7f296.jpg)

**Comment by daftspunk** [comment]
I can't seem to replicate this problem...

**Comment by kelly001** [comment]
Hi! I've found reason why this form was empty. It seems that I did not have any notification event to which I could apply a rule.  After I've added "Invoice for Shopaholic" plugin It worked correctly. 

Sorry for bothering you.
