### ISSUE TITLE
ExecutionContextCondition not evaluating 'theme' and 'context' conditions?

### ISSUE THREAD

**Issue by abrenoch** [rainlab/notify-plugin#40]
Hi sorry if I'm mistaken about this, but it seems like `ExecutionContextCondition` is not evaluating either the `theme` or `context` options.

Here is a copy of the current `isTrue` function for that:
```
    public function isTrue(&$params)
    {
        $hostObj = $this->host;
        $attribute = $hostObj->subcondition;

        $conditionValue = $hostObj->value;
        $conditionValue = trim(mb_strtolower($conditionValue));

        if ($attribute == 'locale') {
            return array_get($params, 'appLocale') == $conditionValue;
        } else if ($attribute === 'environment') {
            return $conditionValue === \App::environment();
        }

        return false;
    }
  ```

I see the context variables `isBackend` and `isConsole` are made available in `Notifier.php`, which could probably be used for evaluating the `context` at least...

Or if I missed something please let me know!

EDIT: I do have a patched version of this condition that is working for me if you are open to a PR

**Comment by daftspunk** [comment]
Yes, sure a PR would be great!
