### ISSUE TITLE
Manage timing of notifications

### ISSUE THREAD

**Issue by frthjf** [rainlab/notify-plugin#6]
I would be good if there was an option to manage the timing of notifications/actions. For instance, sending a reminder 1 month after a user signed up etc.

**Comment by LukeTowers** [comment]
How would you suggest implementing this?

**Comment by frthjf** [comment]
I think it would be possible to implement it as an action type "timed action" that schedules another action X. The timed action would take the point in time (relative or absolute) and the target notify action X. Once triggered in step 8 in the [notification workflow](https://github.com/rainlab/notify-plugin#notification-workflow), the timed action schedules the action X according to the time plan using [Queues](https://laravel.com/docs/5.5/queues). In the UI, the user should have the option to configure the a time plan after she hits the Save button of an action. If the user configures time planning, the action is wrapped in a timed action before being saved to the actions list.

**Comment by LukeTowers** [comment]
@frthjf I'd love to see a PR for this

**Comment by frthjf** [comment]
Great, I'll crack on with this then

**Comment by daftspunk** [comment]
Moved to #7
